### ISSUE TITLE
Server crashes trying to start dub

### ISSUE THREAD

**Issue by vladimmi** [Pure-D/serve-d#3] opened 2017-08-21 11:55 UTC
I have LDC installed, successfully compiled serve-d with `dub build`.
Then installed code-d in Code and specified full paths for every component needed in user settings (for `dub`, `serve-d`, `dfmt`, etc). But when I open any D project I have an error message saying `The code-d & serve-d server crashed 5 times in the last 3 minutes. The server will not be restarted.` and this output in console:
```
2017-08-21T14:41:58.609:source\app.d:main:201 Features fulfilled
2017-08-21T14:41:58.609:source\app.d:main:205 Started reading from stdin
2017-08-21T14:41:58.609:source\app.d:main:209 RPC started
2017-08-21T14:41:58.620:source\app.d:main:220 Has Message
2017-08-21T14:41:58.620:source\app.d:main:222 Message: RequestMessage(0, "initialize", {"capabilities":{"textDocument":{"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"hover":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"synchronization":{"didSave":true,"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true}},"workspace":{"applyEdit":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true},"workspaceEdit":{"documentChanges":true}}},"processId":7092,"rootPath":"d:\\Workspace\\d\\serve-d","rootUri":"file:\/\/\/d%3A\/Workspace\/d\/serve-d","trace":"off"})
2017-08-21T14:41:58.631:source\app.d:__lambda10:228 Processing as request
2017-08-21T14:41:58.631:source\app.d:processRequest:50 Initializing
2017-08-21T14:41:58.631:source\served\extension.d:initialize:139 Initializing serve-d for d:\Workspace\d\serve-d
2017-08-21T14:41:58.631:source\served\extension.d:initialize:152 Starting dub...
[Info  - 14:41:58] Connection to server got closed. Server will restart.
```
This repeats several times until...
```
[Error - 14:41:58] Connection to server got closed. Server will not be restarted.
```

**Comment by WebFreak001** [comment] 2017-08-21 15:05
compile serve-d with `dub build --compiler=ldc2 --combined`, otherwise the issue you have there can happen.

Otherwise try running it again on a empty dub project without any dependencies first?

**Comment by vladimmi** [comment] 2017-08-21 16:20
My actual compile command was `dub build --build=release --arch=x86_64 --compiler=ldc2`. Tried adding `--combined` - nothing changed, same crash on start. Also same crash with simple project containing single `app.d` without any dependencies.

**Comment by WebFreak001** [comment] 2017-08-21 18:00
try dropping the arch and build type?

**Comment by vladimmi** [comment] 2017-08-21 18:22
That only changed build from `release` to `debug` but still crashing. Gonna try x86 build too in case it matters.

**Comment by vladimmi** [comment] 2017-08-21 18:37
With x86 debug build log changed a bit and crashes at other places:
```
2017-08-21T21:28:30.634:source\app.d:processRequest:77 Calling provideDocumentSymbols
[Info  - 21:28:30] Connection to server got closed. Server will restart.
```
...once and then 4 times at...
```
2017-08-21T21:28:30.943:source\app.d:main:222 Message: RequestMessage(none, "$/setTraceNotification", {"value":"off"})
[Info  - 21:28:30] Connection to server got closed. Server will restart.
```
Reloading window another time and first crash is at:
```
2017-08-21T21:33:21.372:source\app.d:main:222 Message: RequestMessage(7, "served/listDependencies", "")
[Info  - 21:33:21] Connection to server got closed. Server will restart.
```
Then several more reloads - and it crashed less than 5 times (same on `setTraceNotification` but not every time) and works. Looks like a bit random...

**Comment by WebFreak001** [comment] 2017-08-25 16:37
Does it happen if you have a specific file open? Try if that crash now happens on the empty project.

**Comment by vladimmi** [comment] 2017-08-25 16:39
Do you mean empty like no d-files at all? Because I've tried to create basic project with `dub init` and it crashes server too.

**Comment by WebFreak001** [comment] 2017-08-25 16:43
no just a `import std.stdio; void main() {}` program. Also whats your `ldc2 --version`?

**Comment by vladimmi** [comment] 2017-08-25 16:45
Ok, just a moment... Also it looks like extension updated and compiling serve-d itself right now, will check if this gonna change something.

**Comment by vladimmi** [comment] 2017-08-25 16:51
Fresh-compiled serve-d was automatically added to user settings, like `"d.servedPath": "C:\\Users\\vladi\\AppData\\Roaming\\code-d\\bin\\serve-d\\serve-d.exe"`. Still crash both on real project and empty one.

LDC version (I believe it to be recent binary release but can try to compile myself from source if that helps):
```
C:\Users\vladi>ldc2 --version
LDC - the LLVM D compiler (1.3.0):
  based on DMD v2.073.2 and LLVM 3.9.1
  built with LDC - the LLVM D compiler (1.3.0)
  Default target: x86_64-pc-windows-msvc
  Host CPU: sandybridge
  http://dlang.org - http://wiki.dlang.org/LDC

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_be - AArch64 (big endian)
    arm        - ARM
    arm64      - ARM64 (little endian)
    armeb      - ARM (big endian)
    ppc32      - PowerPC 32
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
```

**Comment by hipolipolopigus** [comment] 2017-08-29 14:39
The crash around `Starting dub...` appears to be caused by having dependencies which aren't subpackages, irrespective of how serve-d/etc are compiled. I've set up [a repo](/hipolipolopigus/serve-d-test) with branches for some examples.

- No dependencies: Functional
- Subpackage dependency: Functional
- Dub dependency: Non-Functional

Using Win10x64, and ldc2 `1.4.0-beta1-win64-msvc`, but I've been having this issue on `1.3.0-win64-msvc` as well.

**Comment by vladimmi** [comment] 2017-08-29 14:49
@hipolipolopigus `master` is "no dependencies", right? Anyway, same crash after `Starting dub...` for me - on every branch from 3 available.

Tried `workspace-d` and corresponding extension (previous, not a beta with `serve-d`) to compare - all branches functional, no crashes for `workspace-d`.

**Comment by hipolipolopigus** [comment] 2017-08-30 07:31
@vladimmi That's correct. I suppose I should've figured it was a different issue, crashing around `Starting dub...` is the only real similarity between your situation and mine.

**Comment by vladimmi** [comment] 2017-08-30 07:43
@WebFreak001 is it possible to run serve-d manually outside of extension and let it connect to already running server? I hope to compile debug version of it and actually run with a debugger then to get more details about crashes.

**Comment by hipolipolopigus** [comment] 2017-08-30 08:00
Hm, scratch my input here. All branches of that testing repo are now failing here, too. No changes other than reinstalling from scratch, which was also done before testing the repo and posting it here.

Weird.

**Comment by Heromyth** [comment] 2017-09-03 00:54
I also have this problem on Windows 10 x64 with ldc2 1.4.0-beta1-win64-msvc. In fact, code-d with latest workspace-d doesn't work. The error message also means the connection to server failed. However, the lates code-d with [workspace-d v2.11.0](https://github.com/Pure-D/workspace-d/releases/download/v2.11.0/workspace-d-2.11.0-windows.zip) works well.

**Comment by WebFreak001** [comment] 2018-04-03 19:53
should be fixed as of latest workspace-d

**Closed by WebFreak001** 2018-04-03 19:53 UTC
