### ISSUE TITLE
Malwarebytes thinks serve-d.exe is malware on windows.

### ISSUE THREAD

**Issue by gdoenlen** [Pure-D/serve-d#106] opened 2020-09-12 16:46 UTC
Probably nothing you can do, but you might want to reach out to them. 

```
File: 1
Generic.Malware/Suspicious, C:\USERS\GEORGE\APPDATA\ROAMING\CODE-D\BIN\SERVE-D.EXE, No Action By User, 0, 392686, 1.0.29743, , shuriken, , E5F2D42CAB1283519CA1190867D4CC7F, DA11CFC9A0618BFB95BDC012CD9B890116D3F65F727A64BED8D7D332460A8524
```

**Comment by WebFreak001** [comment] 2020-09-12 16:46
duplicate of #87

**Closed by WebFreak001** 2020-09-12 16:46 UTC

**Comment by ZHANITEST** [comment] 2020-09-19 10:05
Hi @gdoenlen. Take this: 

# DUB options
* --build: release
* --compiler: ldc2, LDC - the LLVM D compiler (1.23.0)
* --arch: x86_64

# VirusTotal
* [56a37450d2f2c807a1eb5359ef7c5de1ffeb1dca83d71c810070361987e53eca](https://www.virustotal.com/gui/file/56a37450d2f2c807a1eb5359ef7c5de1ffeb1dca83d71c810070361987e53eca/detection)


Thanks.
